esphome:
  name: esphome-zehnder-fan
  friendly_name: ESPHome Zehnder fan

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  - platform: esphome
    password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .fritz.box

# SPI configuration for nRF905
spi:
  clk_pin: GPIO21
  mosi_pin: GPIO19
  miso_pin: GPIO20

# External components
external_components:
  - source:
      type: git
      url: https://github.com/srslynow/esphome-zehnder
      ref: main
    refresh: 60sec
    components: [zehnder_fan]

# Fan configuration
fan:
  - platform: zehnder_fan
    id: ventilation_fan
    name: "Mechanical Ventilation"
    
    # Required Pin Configuration
    cs_pin: GPIO18
    pwr_pin: GPIO15
    ce_pin: GPIO5
    txen_pin: GPIO7
    dr_pin: GPIO23

services:
  - service: start_pairing
    then:
      - lambda: |-
          id(ventilation_fan).start_pairing();
